# Generated by Django 4.0.5 on 2022-06-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Feriado')),
                ('dia', models.IntegerField(verbose_name='Data')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ano', models.IntegerField(default=2022)),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
            ],
        ),
        migrations.CreateModel(
            name='FeriadoModelApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='feriado')),
                ('data', models.DateField(verbose_name='data')),
            ],
        ),
    ]
